# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0004_auto_20190624_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='guest',
        ),
        migrations.AddField(
            model_name='trip',
            name='guest',
            field=models.ManyToManyField(blank=True, null=True, related_name='trips', to='trip_buddy.User'),
        ),
    ]
