# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0005_auto_20190624_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='guest',
            field=models.ManyToManyField(related_name='trips', to='trip_buddy.User'),
        ),
    ]
